name: BPF

on:
  - pull_request

jobs:
    coccicheck:
        name: coccicheck
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - uses: docker://cilium/coccicheck:latest
